### ISSUE TITLE
UnboundLocalError when calling non existent post id

### ISSUE THREAD

**Issue by rbaertschi** [muellermichel/guetzli#2]
Opening a URL with non existent post id results in an UnboundLocalError. Instead it should probably return a 404 response.

Example: Opening "/en/001-about/1" where language "en" and page "001-about" exist results in the above mentioned error.

![image](https://cloud.githubusercontent.com/assets/10210710/11803847/10b21b48-a2ff-11e5-8b04-b97d53cd061f.png)

**Comment by muellermichel** [comment]
Fixed with current commit, now redirects to default page (in line with how pages behave).
